name = "node-video-proxy"
compatibility_date = "2024-01-01"

# KV Database binding
[[kv_namespaces]]
binding = "VIDEO_PROXY_DB"
id = "YOUR_KV_NAMESPACE_ID_HERE" # User needs to replace this
preview_id = "YOUR_KV_NAMESPACE_ID_HERE"

[observability]
enabled = true
head_sampling_rate = 1
